DROP TYPE IF EXISTS difficulty;
CREATE TYPE difficulty AS ENUM (
    'easy',
    'medium',
    'hard'
);

CREATE TABLE IF NOT EXISTS scores (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    score INTEGER NOT NULL,
    difficulty difficulty NOT NULL
);
